
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lyss?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  resources:
    static-locations: classpath:/static/



mybatis:
  type-aliases-package: cn.lys.motherland.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true




logging:
  level:
    cn:
      lys:
        motherland:
          mapper: debug

